# Generated by Django 4.2.5 on 2023-09-30 09:12

from django.db import migrations

def populate(apps, schemaeditor):
    entries = {
        "developer": "A person tasked with completing issues", 
        "scrum master": "The development team's coach",
        "product owner": "A team member who defines tasks",
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Team(name=key, description=value)
        role_obj.save()
        
def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "The A team",
        "bravo": "The B team",
        "charlie": "The C team",
        "delta": "The D team"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()
        
           

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_role),
        migrations.Runpython(populate_team)
    ]
